BEGIN;

-- ============================================================
-- Drop existing tables
-- CASCADE is used because PostgreSQL enforces dependencies.
-- ============================================================

DROP TABLE IF EXISTS attendance CASCADE;
DROP TABLE IF EXISTS marks CASCADE;
DROP TABLE IF EXISTS admin CASCADE;
DROP TABLE IF EXISTS attandance CASCADE;
DROP TABLE IF EXISTS basic CASCADE;
DROP TABLE IF EXISTS chat CASCADE;
DROP TABLE IF EXISTS courses CASCADE;
DROP TABLE IF EXISTS faculties CASCADE;
DROP TABLE IF EXISTS notification CASCADE;
DROP TABLE IF EXISTS result CASCADE;
DROP TABLE IF EXISTS rollgenerator CASCADE;
DROP TABLE IF EXISTS students CASCADE;
DROP TABLE IF EXISTS subject CASCADE;


-- ============================================================
-- Table: admin
-- ============================================================

CREATE TABLE admin (
                       collagename VARCHAR(50) DEFAULT NULL,
                       address VARCHAR(100) DEFAULT NULL,
                       emailid VARCHAR(255) NOT NULL,
                       contactnumber VARCHAR(40) DEFAULT NULL,
                       website VARCHAR(30) DEFAULT NULL,
                       lastlogin VARCHAR(40) DEFAULT NULL,
                       password VARCHAR(255) DEFAULT NULL,
                       facebook VARCHAR(100) DEFAULT NULL,
                       instagram VARCHAR(100) DEFAULT NULL,
                       twitter VARCHAR(100) DEFAULT NULL,
                       linkedin VARCHAR(100) DEFAULT NULL,
                       logo VARCHAR(255) DEFAULT NULL,
                       activestatus SMALLINT DEFAULT 0,
                       PRIMARY KEY (emailid)
);

INSERT INTO admin (
    collagename,
    address,
    emailid,
    contactnumber,
    website,
    lastlogin,
    password,
    facebook,
    instagram,
    twitter,
    linkedin,
    logo,
    activestatus
) VALUES (
             'Government College of Engineering, Keonjhar',
             'Jamunalia, Keonjhar, Odisha ',
             'admin@gcekjr.ac.in',
             '0000000000',
             'http://geckjr.ac.in',
             '2026-03-21T17:28:00.311Z',
             '$2b$10$dWTjLOwtAaGrlZ4CAbTud.FGDvmDj.WOI3sDsRUQlpiNFnNrkesK.',
             'https://facebook.com/gcekjr',
             'https://instagram.com/gcekjr',
             'https://x.com/gcekjr',
             'https://linkedin.com/gcekjr ',
             '/uploads/admin/admin.jpg',
             1
         );


-- ============================================================
-- Table: attandance
-- Original misspelled table name preserved.
-- ============================================================

CREATE TABLE attandance (
                            subjectcode VARCHAR(30) DEFAULT NULL,
                            date VARCHAR(30) DEFAULT NULL,
                            rollnumber BIGINT DEFAULT NULL,
                            present SMALLINT DEFAULT 0,
                            courcecode VARCHAR(20) DEFAULT NULL,
                            semoryear INTEGER DEFAULT NULL
);


-- ============================================================
-- Table: basic
-- ============================================================

CREATE TABLE basic (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                       PRIMARY KEY (id),
                       CONSTRAINT basic_id_unique UNIQUE (id)
);


-- ============================================================
-- Table: chat
-- ============================================================

CREATE TABLE chat (
                      sr_no INTEGER GENERATED BY DEFAULT AS IDENTITY,
                      fromuserid VARCHAR(70) DEFAULT NULL,
                      fromusername VARCHAR(50) DEFAULT NULL,
                      touserid VARCHAR(70) DEFAULT NULL,
                      message TEXT,
                      messagetime VARCHAR(20) DEFAULT NULL,
                      messagedate VARCHAR(40) DEFAULT NULL,
                      readby TEXT,
                      PRIMARY KEY (sr_no)
);


-- ============================================================
-- Table: courses
-- ============================================================

CREATE TABLE courses (
                         id INTEGER GENERATED BY DEFAULT AS IDENTITY,
                         course_code VARCHAR(20) NOT NULL,
                         course_name VARCHAR(100) NOT NULL,
                         total_semesters INTEGER NOT NULL,
                         created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                         updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                         sem_or_year VARCHAR(4) NOT NULL DEFAULT 'sem',

                         PRIMARY KEY (id),

                         CONSTRAINT courses_course_code_unique
                             UNIQUE (course_code),

                         CONSTRAINT courses_course_name_unique
                             UNIQUE (course_name),

                         CONSTRAINT courses_sem_or_year_check
                             CHECK (sem_or_year IN ('sem', 'year'))
);

INSERT INTO courses (
    id,
    course_code,
    course_name,
    total_semesters,
    created_at,
    updated_at,
    sem_or_year
) VALUES
      (
          9,
          'CSE',
          'Computer Science & Engineering',
          8,
          '2026-02-25 12:32:58',
          '2026-02-25 12:32:58',
          'sem'
      ),
      (
          10,
          'IT',
          'Information Technology',
          8,
          '2026-02-25 12:33:26',
          '2026-02-25 12:33:26',
          'sem'
      ),
      (
          15,
          'BCA',
          'Bachelor In Computer Application',
          3,
          '2026-03-01 09:55:38',
          '2026-03-01 09:55:38',
          'year'
      );


-- ============================================================
-- PostgreSQL replacement for:
--
-- updated_at TIMESTAMP
-- DEFAULT CURRENT_TIMESTAMP
-- ON UPDATE CURRENT_TIMESTAMP
-- ============================================================

CREATE OR REPLACE FUNCTION update_courses_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER courses_updated_at_trigger
    BEFORE UPDATE ON courses
    FOR EACH ROW
    EXECUTE FUNCTION update_courses_updated_at();


-- ============================================================
-- Table: faculties
-- ============================================================

CREATE TABLE faculties (
                           facultyid INTEGER NOT NULL,
                           facultyname VARCHAR(30) DEFAULT NULL,
                           state VARCHAR(30) DEFAULT NULL,
                           city VARCHAR(30) DEFAULT NULL,
                           emailid VARCHAR(50) DEFAULT NULL,
                           contactnumber VARCHAR(20) DEFAULT NULL,
                           qualification VARCHAR(30) DEFAULT NULL,
                           experience VARCHAR(30) DEFAULT NULL,

    -- Changed from VARCHAR because PostgreSQL TO_CHAR()
    -- in facultyController.js expects a date value.
                           birthdate DATE DEFAULT NULL,

                           gender VARCHAR(10) DEFAULT NULL,
                           profilepic VARCHAR(255) DEFAULT NULL,
                           courcecode VARCHAR(20) DEFAULT 'NOT ASSIGNED',
                           semoryear INTEGER DEFAULT 0,
                           subject VARCHAR(40) DEFAULT 'NOT ASSIGNED',
                           position VARCHAR(40) DEFAULT 'NOT ASSIGNED',
                           sr_no INTEGER GENERATED BY DEFAULT AS IDENTITY,
                           lastlogin VARCHAR(100) DEFAULT NULL,
                           password VARCHAR(255) DEFAULT NULL,
                           activestatus SMALLINT DEFAULT 0,
                           joineddate DATE DEFAULT NULL,

                           PRIMARY KEY (sr_no),

                           CONSTRAINT faculties_facultyid_unique
                               UNIQUE (facultyid),

                           CONSTRAINT faculties_emailid_unique
                               UNIQUE (emailid)
);

INSERT INTO faculties (
    facultyid,
    facultyname,
    state,
    city,
    emailid,
    contactnumber,
    qualification,
    experience,
    birthdate,
    gender,
    profilepic,
    courcecode,
    semoryear,
    subject,
    position,
    sr_no,
    lastlogin,
    password,
    activestatus,
    joineddate
) VALUES (
             23011050,
             'John',
             'Odisha',
             'Bhubaneswar',
             'example@gmail.com',
             '9876543210',
             'MCA',
             '5 Years',
             '2000-02-01',
             'Female',
             '23011050.jpg',
             'CSE',
             6,
             '603',
             'Assistant Professor',
             121,
             '2026-03-19T15:28:39.902Z',
             '$2b$10$NMoy0KUxl4tsVGHZ5Xjs4.CLrZ6Qdvkii6eENxi2Zjwh1SN8jSzEy',
             1,
             '2026-03-10'
         );


-- ============================================================
-- Table: notification
-- ============================================================

CREATE TABLE notification (
                              sr_no INTEGER GENERATED BY DEFAULT AS IDENTITY,
                              userprofile VARCHAR(30) DEFAULT NULL,
                              courcecode VARCHAR(30) DEFAULT NULL,
                              semoryear INTEGER DEFAULT NULL,
                              userid VARCHAR(30) DEFAULT NULL,
                              title VARCHAR(100) DEFAULT NULL,
                              message VARCHAR(1000) DEFAULT NULL,
                              time VARCHAR(100) DEFAULT NULL,
                              readby TEXT,
                              PRIMARY KEY (sr_no)
);


-- ============================================================
-- Table: result
-- ============================================================

CREATE TABLE result (
                        courcecode VARCHAR(30) NOT NULL,
                        semoryear INTEGER NOT NULL,
                        isdeclared SMALLINT DEFAULT NULL,

                        PRIMARY KEY (courcecode, semoryear)
);


-- ============================================================
-- Table: rollgenerator
-- ============================================================

CREATE TABLE rollgenerator (
                               courcecode VARCHAR(20) NOT NULL,
                               semoryear INTEGER NOT NULL,
                               rollnumber BIGINT DEFAULT NULL,

                               PRIMARY KEY (courcecode, semoryear)
);


-- ============================================================
-- Table: students
--
-- MySQL column name `Courcecode` becomes lowercase courcecode
-- in PostgreSQL because unquoted identifiers are folded to
-- lowercase.
-- ============================================================

CREATE TABLE students (
                          courcecode VARCHAR(20) DEFAULT NULL,
                          semoryear INTEGER DEFAULT NULL,
                          rollnumber BIGINT DEFAULT NULL,
                          optionalsubject VARCHAR(30) DEFAULT NULL,
                          firstname VARCHAR(20) DEFAULT NULL,
                          lastname VARCHAR(20) DEFAULT NULL,
                          emailid VARCHAR(50) DEFAULT NULL,
                          contactnumber VARCHAR(20) DEFAULT NULL,
                          dateofbirth VARCHAR(15) DEFAULT NULL,
                          gender VARCHAR(10) DEFAULT NULL,
                          state VARCHAR(30) DEFAULT NULL,
                          city VARCHAR(30) DEFAULT NULL,
                          fathername VARCHAR(20) DEFAULT NULL,
                          fatheroccupation VARCHAR(30) DEFAULT NULL,
                          mothername VARCHAR(30) DEFAULT NULL,
                          motheroccupation VARCHAR(30) DEFAULT NULL,
                          profilepic VARCHAR(255) DEFAULT NULL,
                          sr_no INTEGER GENERATED BY DEFAULT AS IDENTITY,
                          lastlogin VARCHAR(100) DEFAULT NULL,
                          password VARCHAR(255) DEFAULT NULL,
                          activestatus SMALLINT DEFAULT 0,
                          admissiondate VARCHAR(50) DEFAULT NULL,

                          PRIMARY KEY (sr_no),

                          CONSTRAINT students_emailid_unique
                              UNIQUE (emailid),

                          CONSTRAINT students_rollnumber_unique
                              UNIQUE (rollnumber)
);

INSERT INTO students (
    courcecode,
    semoryear,
    rollnumber,
    optionalsubject,
    firstname,
    lastname,
    emailid,
    contactnumber,
    dateofbirth,
    gender,
    state,
    city,
    fathername,
    fatheroccupation,
    mothername,
    motheroccupation,
    profilepic,
    sr_no,
    lastlogin,
    password,
    activestatus,
    admissiondate
) VALUES
      (
          'CSE',
          1,
          23011006,
          NULL,
          'Amir',
          'khan',
          'amir@gcekjr.ac.in',
          '9876543210',
          '2003-01-06',
          'Male',
          'Odisha',
          'Bhubaneswar',
          NULL,
          NULL,
          NULL,
          NULL,
          '23011006.jpg',
          23,
          '2026-03-18T07:18:16.538Z',
          '$2b$10$f69fZK2wuNANAtAt.BHJKeJAKxC.OWXZuZ7lSmFqdgBjWzL.c3jxa',
          1,
          '2026-03-01'
      ),
      (
          'BCA',
          1,
          23011007,
          'Mathematics',
          'Aman',
          'Sharma',
          'student22@gcekjr.ac.in',
          '9867896540',
          '2000-11-25',
          'Male',
          'Odisha',
          'Keonjhar',
          'Rajesh Sharma',
          'Businessman',
          'Sunita Sharma',
          'Teacher',
          '23011007.jpg',
          28,
          '2026-03-19T06:25:08.338Z',
          '$2b$10$9yiGT7TqohIQ9fgbmf0IsOayhaO7WY4dlKcI0lfLR/Ea.Aq.pbvcm',
          1,
          '2026-03-03'
      ),
      (
          'BCA',
          1,
          23011001,
          NULL,
          'Rahul',
          'Kumar',
          'rahul@example.com',
          '9876543210',
          '2003-01-01',
          'Male',
          'Odisha',
          'Bhubaneswar',
          NULL,
          NULL,
          NULL,
          NULL,
          '23011001.jpg',
          29,
          NULL,
          '$2b$10$B/MecBkLO5jkopucDkKxVe7zfTJyJiDLpwsAqeh30eQcDWjhbthfq',
          NULL,
          '2026-03-17'
      ),
      (
          'CSE',
          1,
          23011009,
          NULL,
          'Student1',
          '',
          'example.com',
          '0000000000',
          '2000-10-11',
          'Female',
          'Odisha',
          'Keonjhar',
          'Rajesh Sharma',
          'Businessman',
          'Sunita Sharma',
          'Teacher',
          '23011009.jpg',
          34,
          NULL,
          '$2b$10$I2aHx8.gaTOuS1Ql8scwL.F/ukhgat/jLJ4gz9L3RL7GNhWZ3mi',
          NULL,
          '2026-03-18'
      );


-- ============================================================
-- Table: subject
-- ============================================================

CREATE TABLE subject (
                         subjectcode VARCHAR(20) DEFAULT NULL,
                         subjectname VARCHAR(50) DEFAULT NULL,
                         courcecode VARCHAR(20) DEFAULT NULL,
                         semoryear INTEGER DEFAULT NULL,
                         subjecttype VARCHAR(30) DEFAULT NULL,
                         theorymarks INTEGER DEFAULT NULL,
                         practicalmarks INTEGER DEFAULT NULL,

                         CONSTRAINT subject_subjectcode_unique
                             UNIQUE (subjectcode),

                         CONSTRAINT subject_unique
                             UNIQUE (subjectcode, courcecode, semoryear)
);

INSERT INTO subject (
    subjectcode,
    subjectname,
    courcecode,
    semoryear,
    subjecttype,
    theorymarks,
    practicalmarks
) VALUES
      ('CSE001', 'Operating Systems', 'CSE', 1, 'core', 100, 50),
      ('CSE002', 'Discrete Mathematics', 'CSE', 1, 'core', 100, 0),
      ('CSE003', 'Artificial Intelligence & Machine Learning', 'CSE', 1, 'core', 100, 50),
      ('CSE004', 'Software Engineering', 'CSE', 1, 'core', 100, 50),
      ('CSE005', 'Compiler Design', 'CSE', 1, 'core', 100, 50),
      ('CSE006', 'Computer Graphics', 'CSE', 1, 'core', 100, 0),
      ('BCA1004', 'Physics', 'BCA', 1, 'core', 100, 50),
      ('601', 'compiler design', 'CSE', 6, 'core', 5, 10),
      ('602', 'ml', 'CSE', 6, 'core', 5, 12),
      ('603', 'computer networking', 'CSE', 6, 'core', 5, 10),
      ('501', 'toc', 'CSE', 5, 'core', 5, 12),
      ('502', 'dbms', 'CSE', 5, 'core', 5, 10),
      ('503', 'data analytics', 'CSE', 5, 'core', 5, 5);


-- ============================================================
-- Table: attendance
-- ============================================================

CREATE TABLE attendance (
                            id INTEGER GENERATED BY DEFAULT AS IDENTITY,
                            student_id INTEGER NOT NULL,
                            subjectcode VARCHAR(30) NOT NULL,
                            attendance_date DATE NOT NULL,
                            present SMALLINT NOT NULL DEFAULT 0,
                            courcecode VARCHAR(20) NOT NULL,
                            semoryear INTEGER NOT NULL,

                            PRIMARY KEY (id),

                            CONSTRAINT unique_attendance
                                UNIQUE (
                                        student_id,
                                        subjectcode,
                                        attendance_date,
                                        courcecode,
                                        semoryear
                                    ),

                            CONSTRAINT fk_attendance_student
                                FOREIGN KEY (student_id)
                                    REFERENCES students (sr_no)
                                    ON DELETE CASCADE,

                            CONSTRAINT fk_attendance_subject
                                FOREIGN KEY (subjectcode)
                                    REFERENCES subject (subjectcode)
                                    ON DELETE CASCADE
);

CREATE INDEX idx_lookup
    ON attendance (
                   subjectcode,
                   courcecode,
                   semoryear,
                   attendance_date
        );

INSERT INTO attendance (
    id,
    student_id,
    subjectcode,
    attendance_date,
    present,
    courcecode,
    semoryear
) VALUES
      (133, 23, 'CSE001', '2026-03-09', 1, 'CSE', 1),
      (134, 28, 'CSE001', '2026-03-09', 0, 'CSE', 1),
      (135, 23, 'CSE001', '2026-03-03', 1, 'CSE', 1),
      (136, 28, 'CSE001', '2026-03-03', 0, 'CSE', 1),
      (141, 23, 'CSE001', '2026-03-10', 1, 'CSE', 1),
      (142, 28, 'CSE001', '2026-03-10', 0, 'CSE', 1),
      (143, 23, 'CSE001', '2026-03-11', 1, 'CSE', 1),
      (145, 34, 'CSE001', '2026-03-03', 1, 'CSE', 1),
      (147, 23, 'CSE001', '2026-03-20', 1, 'CSE', 1),
      (148, 34, 'CSE001', '2026-03-20', 1, 'CSE', 1),
      (149, 23, 'CSE001', '2026-03-02', 1, 'CSE', 1),
      (150, 34, 'CSE001', '2026-03-02', 1, 'CSE', 1),
      (151, 23, 'CSE005', '2026-03-21', 0, 'CSE', 1),
      (152, 34, 'CSE005', '2026-03-21', 1, 'CSE', 1);


-- ============================================================
-- Table: marks
-- ============================================================

CREATE TABLE marks (
                       courcecode VARCHAR(20) DEFAULT NULL,
                       semoryear INTEGER DEFAULT NULL,
                       subjectcode VARCHAR(20) DEFAULT NULL,
                       subjectname VARCHAR(100) DEFAULT NULL,
                       rollnumber BIGINT DEFAULT NULL,
                       theorymarks INTEGER DEFAULT NULL,
                       practicalmarks INTEGER DEFAULT NULL,

                       CONSTRAINT unique_marks
                           UNIQUE (
                                   courcecode,
                                   semoryear,
                                   subjectcode,
                                   rollnumber
                               ),

                       CONSTRAINT fk_marks_student
                           FOREIGN KEY (rollnumber)
                               REFERENCES students (rollnumber)
                               ON DELETE CASCADE,

                       CONSTRAINT fk_marks_subject
                           FOREIGN KEY (subjectcode)
                               REFERENCES subject (subjectcode)
                               ON DELETE CASCADE
);

CREATE INDEX idx_marks_rollnumber
    ON marks (rollnumber);

CREATE INDEX idx_marks_subjectcode
    ON marks (subjectcode);

INSERT INTO marks (
    courcecode,
    semoryear,
    subjectcode,
    subjectname,
    rollnumber,
    theorymarks,
    practicalmarks
) VALUES
      ('CSE', 1, 'CSE001', 'Operating Systems', 23011006, 0, 0),
      ('CSE', 1, 'CSE001', 'Operating Systems', 23011007, 94, 42),
      ('CSE', 1, 'CSE002', 'Discrete Mathematics', 23011006, 90, 0),
      ('CSE', 1, 'CSE003', 'Artificial Intelligence & Machine Learning', 23011006, 90, 50),
      ('CSE', 1, 'CSE003', 'Artificial Intelligence & Machine Learning', 23011007, 85, 40),
      ('CSE', 1, 'CSE004', 'Software Engineering', 23011006, 76, 47),
      ('CSE', 1, 'CSE004', 'Software Engineering', 23011007, 72, 43),
      ('CSE', 1, 'CSE005', 'Compiler Design', 23011006, 93, 44),
      ('CSE', 1, 'CSE005', 'Compiler Design', 23011007, 92, 47),
      ('CSE', 1, 'CSE006', 'Computer Graphics', 23011006, 95, 0),
      ('CSE', 1, 'CSE006', 'Computer Graphics', 23011007, 76, 0),
      ('CSE', 1, 'CSE002', 'Discrete Mathematics', 23011007, 23, 0),
      ('CSE', 1, 'CSE001', 'Operating Systems', 23011009, 0, 0);


-- ============================================================
-- Synchronize identity sequences with imported MySQL IDs
-- ============================================================

SELECT setval(
               pg_get_serial_sequence('courses', 'id'),
               COALESCE((SELECT MAX(id) FROM courses), 1),
               true
       );

SELECT setval(
               pg_get_serial_sequence('faculties', 'sr_no'),
               COALESCE((SELECT MAX(sr_no) FROM faculties), 1),
               true
       );

SELECT setval(
               pg_get_serial_sequence('students', 'sr_no'),
               COALESCE((SELECT MAX(sr_no) FROM students), 1),
               true
       );

SELECT setval(
               pg_get_serial_sequence('attendance', 'id'),
               COALESCE((SELECT MAX(id) FROM attendance), 1),
               true
       );

SELECT setval(
               pg_get_serial_sequence('basic', 'id'),
               COALESCE((SELECT MAX(id) FROM basic), 1),
               true
       );

SELECT setval(
               pg_get_serial_sequence('chat', 'sr_no'),
               COALESCE((SELECT MAX(sr_no) FROM chat), 1),
               true
       );

SELECT setval(
               pg_get_serial_sequence('notification', 'sr_no'),
               COALESCE((SELECT MAX(sr_no) FROM notification), 1),
               true
       );

COMMIT;
